# This workflow will do a clean install of node dependencies, build the source code of the backend and run 
# tests across different versions of node

name: Node.js CI / Backend Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd Backend/
    - run: npm install --save jest chai
    - run: npm install --save request
    - run: npm install --save express
    - run: npm install
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
